# Stage 1: Build the React application
FROM node:alpine as builder

WORKDIR /OperatorApp/Frontend/operator-app

COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install
# If you use yarn, replace the above with:
# RUN yarn install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/

# Copy the build output from the builder stage to Nginx
COPY --from=builder /OperatorApp/Frontend/operator-app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]